### ISSUE TITLE
Training custom datasets.

### ISSUE THREAD

**Issue by luosifenq1q** [Championchess/A-Tri-Layer-Plugin-to-Improve-Occluded-Detection#5]
Hi,firstly thank you for the excellent work here!
I would like to know how to train my custom datasets with your model.My datasets format is COCO format.And what other data preprocessing do I need to do for model training?
Thanks!

**Comment by Championchess** [comment]
Thank you for your interest. You might need to generate the occluder/occludee mask for each object using amodal completion and depth reasoning first, as introduced in the paper.
