### ISSUE TITLE
Test on new image

### ISSUE THREAD

**Issue by myhui0524** [Championchess/A-Tri-Layer-Plugin-to-Improve-Occluded-Detection#7]
Hi~ Could you share how to test on new images that do not have .json and then visualize the results?

Thank you very much!

**Comment by Championchess** [comment]
A straight forward way would be make a .json file in the COCO format of the new test set you want which could fit into the mmdetection framework. For visualise, I can share you a function to visualise mask on image

def blend_mask(im, mask, colour=[1, 1, 0], alpha=0.5, show_im=False):
    """Blend an image with a mask (colourised via `colour` and `alpha`)."""
    if type(im) == torch.Tensor:
        im = im.numpy()
    im = im.copy()
    if im.max() > 1:
        im = im.astype(np.float) / 255
    if mask.max() > 1:
        mask = (mask.astype(np.float) / 255).round()
    for ch, rgb_v in zip([0, 1, 2], colour):
        im[:, :, ch][mask == 1] = im[:, :, ch][mask == 1] * (1 - alpha) + rgb_v * alpha
    if show_im:
        plt.imshow(im)
        plt.axis("off")
        plt.show()
    return im * 255

**Comment by Championchess** [comment]
Glad to help! Please cite our paper if you use the code/dataset of this github
